### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Er2ch** [hqsq/tochnonenaeb#1]
*Maybe I refactor this site, but I anyway write bugs here.*

- [ ] On Firefox if enable dark reader, bottom is shows grey instead of black.

- [x] If open console, before warning message an error: `Uncaught TypeError: g is undefined` on `util.js:55`

If you found any bugs, send it here.

**Comment by hqsq** [comment]
Hello, I will fix the problem with the console, what is the dark reader?

**Comment by Er2ch** [comment]
> Hello, I will fix the problem with the console, what is the dark reader?

Dark Reader is an extension for Firefox (and not only) which make dark mode for any site.

**Comment by hqsq** [comment]
Why include a dark mode on a site that consists of two colors (black and white) ???

**Comment by hqsq** [comment]
The JS error is fixed, I will send it to the server later.
